###GET all abilities
GET http://localhost:5000/api/abilities/

###GET one abilities
GET http://localhost:5000/api/abilities/652b315565a3bdd061d52a19


###POST
POST http://localhost:5000/api/abilities/
Content-Type: application/json

{
    "name": "Shock Bolt",
    "description": "EQUIP a bow with a shock bolt. FIRE to send the explosive bolt forward, detonating upon collision and damaging players nearby. HOLD FIRE to extend the range of the projectile. ALT FIRE to add up to two bounces to this arrow.",
    "actionKey": "Q"
}

###PUT
PUT http://localhost:5000/api/abilities/652b315565a3bdd061d52a19

Content-Type: application/json

{
    "name": "Shock volt"
}

###PUT
PUT http://localhost:5000/api/abilities/652b315565a3bdd061d52a19

Content-Type: application/json

{
    "name": "Shock Bolt",
    "description": "EQUIP a bow with a shock bolt. FIRE to send the explosive bolt forward, detonating upon collision and damaging players nearby. HOLD FIRE to extend the range of the projectile. ALT FIRE to add up to two bounces to this arrow.",
    "actionKey": "Q"
}

###DELETE
DELETE http://localhost:5000/api/abilities/652b315565a3bdd061d52a19
