###GET all users
GET http://localhost:5000/api/users/

###GET one user
GET http://localhost:5000/api/users/6528368bc017778e4cce8c8e

###POST
POST http://localhost:5000/api/users/
Content-Type: application/json

{
  "puuid": "qHn0uNkpA1T-NqQ0zHTEqNh1BhH5SAsGWwkttacbeKBqSdkUEaYOcYNjyutq60vMrLWHu4ulYg1C5Q",
  "name_lastname": "el gordo guma",
  "email": "gumayusi@gmail.com",
  "crosshair": "0;P;c;5;o;1;d;1;0b;0",
  "password": "gangplank",
  "agents": ["Omen", "Sage", "Brimstone"]
}

###PUT
PUT http://localhost:5000/api/users/6531acdeed02b3fff89f1817
Content-Type: application/json

{
  "puuid": "qHn0uNkpA1T-NqQ0zasfasfsafsaNjDomm40yMrLWHu4ulYg1C5Q",
  "name_lastname": "Santi Montecino",
  "email": "santimonte@gmail.com",
  "crosshair": "0;P;c;5;o;1;d;1;0b;0",
  "password": "homerochino",
  "agents": ["Jett", "Breach"]
}

###Patch
PATCH http://localhost:5000/api/users/65283ab17883b0be119b8f03
Content-Type: application/json

{
  "email": "gumaguma@gmail.com",
  "crosshair": "0d;1;0b;0",
  "password": "banana"
}

###DELETE
DELETE http://localhost:5000/api/users/6531acdeed02b3fff89f1817